### PR TITLE
Window.navigator: Add support for NavigatorLanguage and NavigatorOnLine

### PR DESCRIPTION
**Pull request by siongui**
Implement according to [Navigator - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator)

### CODE REVIEW

**Comment by dominikh** [comment]
I believe these types should be interfaces, similar to our Window, Document and other interfaces.

**Comment by siongui** [comment]
For NavigatorLanguage and NavigatorOnLine, it is easier and clearer to implement using struct instead of interface. I check other properties of navigator, such as geolocation and etc., I think it is also possible to implement using struct.
PS: NavigatorID (appName, userAgent, etc.) is Deprecated in MDN.

**Comment by siongui** [comment]
The syntax for accessing the property 
**NavigatorLanguage.language** is *window.navigator.language*, 
**NavigatorLanguage.languages** is *window.navigator.languages*, 
**NavigatorOnLine.onLine** is *window.navigator.onLine*.

For me, I would expect to access the property in GopherJS DOM bindings by:
*dom.GetWindow().Navigator().Language*
*dom.GetWindow().Navigator().Languages*
*dom.GetWindow().Navigator().OnLine*

This is similar to how you access the property in JavaScript, which is intuitive for JavaScript programmers who want to try GopherJS DOM binding. This is the main reason to implement in struct way. Could you please give your thoughts on this? Thanks!

**Comment by dominikh** [comment]
Arguing based on the syntax of JavaScript is futile. `dom.GetWindow().Navigator()` already looks nothing like `window.navigator`. Also, intuitiveness for JavaScript programmers is not a goal. This package is designed for Go programmers.

Navigator is an interface for the same reason that Window, Element, HTMLElement and some others are: to simplify replacing them with mocks in tests. And in this particular instance, the DOM explicitly has various Navigator-related interfaces to separate different concerns.

> PS: NavigatorID (appName, userAgent, etc.) is Deprecated in MDN

Is all of NavigatorID deprecated? According to https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID the userAgent attribute is not (and I cannot find any other interface with that attribute, either).

Either way, please stick to the interfaces in the DOM (Navigator, NavigatorLanguage and so on). And an implementation should cover all of the attributes, not selectively implement some and neuter the rest of the interfaces.

**Comment by siongui** [comment]
Thanks for your comments. I understand the concerns now. I am not an expert in the API here so I am not able to understand the API totally and help implement the interface you want right now. Please abandon this pull request, Thanks!

I read the online [NavigatorID API](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID) and it seems all are deprecated. [userAgent](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID) is also deprecated according to MDN.

**Comment by dominikh** [comment]
How are you determining that userAgent is deprecated? It doesn't have that "thumbs down" deprecated icon next to its name from what I can tell.

> Please abandon this pull request, Thanks

I'll see if I can implement it myself in the coming days.

**Comment by siongui** [comment]
Yes, it does have "thumbs down" deprecated icon in the [userAgent](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/userAgent) link. (Do you follow the links I put in my comments?)

**Comment by dominikh** [comment]
The link in your other comment pointed to https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID and not https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/userAgent. The former does not indicate that it is deprecated. The latter does.

And I'm not sure why I'm even still surprised about inaccurate information in the MDN.

**Comment by shurcooL** [comment]
> And I'm not sure why I'm even still surprised about inaccurate information in the MDN.

Does that realization have an effect on #30?

**Comment by shurcooL** [comment]
What's the status here?

> > Please abandon this pull request, Thanks
>
> I'll see if I can implement it myself in the coming days.

Is that still the case? If not, perhaps closing it would be a better way to reflect the current status.

**Comment by dominikh** [comment]
I won't have time to implement this myself. Closing the PR as requested by its author. If anyone else wants to implement this, feel free to.

**Pull request closed without merging**
