### PR TITLE
v2: support go1.14

### PR DESCRIPTION
**Pull request by inliquid**

### CODE REVIEW

**Comment by inliquid** [comment]
Fixes #74 
/cc @dmitshur

**Comment by dmitshur** [comment]
Thanks for starting this work, @inliquid. I've finally had a chance to review.

This looks good and is functional, but I think we should make the following changes:

- Rename the existing `dom.go` and `events.go` to `dom_go113.go` and `events_go113.go`, make the new 1.14+ files be `dom.go` and `events.go` since they're more important.
- Don't convert the switches into if/else if statements, keep them as switches. See https://github.com/dominikh/go-js-dom/issues/74#issuecomment-615941119.

**Comment by inliquid** [comment]
@dmitshur I renamed files as you suggested, however, the proposed `switch/case` construction will not work because `Equal` returns `bool`:
изображение

**Comment by dmitshur** [comment]
Thanks for doing that. Sorry, I missed the notification for this earlier.

I'm quite sure the switch/case construction works, perhaps there was some issue when you tried it. Please see the commit I pushed.

**Comment by inliquid** [comment]
Thank you, I didn't notice that there is nothing after `;` in initialization statement of `switch`. Looks a little bit magical and I would prefer `if/else` as they seem more natural, but anyways...

**Pull request merged**
